### ISSUE TITLE
[Bug]: Broken cargs options for gprbuild

### ISSUE THREAD

**Issue by csaltos** [AdaCore/ada_language_server#1227] opened 2024-12-18 08:55 UTC
### Environment

- OS and Version: Windows 10 Version 22H2 for x64-based Systems
- IDE Version: Visual Studio Code 1.96.0
- Ada & SPARK Extension Version: 26.0.202411173
- Alire Version: 2.0.2+9b80158
- gprbuild version: 22.0.0 x86_64-win64-mingw32

### Bug Summary and Reproducer

Bug Summary: When creating a new project with Alire it cannot be built and run using Visual Studio code with the Ada & SPARK Extension (with Alire it works)

Steps to reproduce:

* Create a initial project with Alire using the command `alr init --bin myproject` 
* Compile and run the project wth Alire using the command `alr run`
* Open Visual Studio with the Ada & Spark Extension installed
* Open the main file and try to compile and run it

Current behavior:

The build step throws these error:

```
gprbuild: illegal option -cargs:ada on the command line
```

This is because the Windows version for `gprbuild` does not support specific Ada options, only general options.

Expected behavior:

The build step succeeds

Possible solutions:

Use the option `-cargs` instead of `-cargs:ada` like new projects are already doing.

Another solution could be to add a setting at configuration level to pass `gprbuild` arguments using the `-cargs` as default, in that sense if someone miss the old options it can be easily changed.

Of course the users can create customs tasks at `task.json` files to attempt to fix this but it's a whole mess, for sure it can be solved at the extension level.

By the way, when using Linux, this works because `gprbuild` on Linux supports specific `-cargs:ada` and also `-cargs` at the same time.

### Configuration and Logs

```shell
Using empty task.json file for running the default extensions tasks
```

### Other VS Code Extensions

The C++ extension

**Comment by reznikmm** [comment] 2024-12-18 11:40
Hello!

`-carg` is an illegal `gprbuild` option. The correct spelling is `-cargs`. The extension never pass `-carg` nor `-carg:ada` to `gprbuild`. It uses `-cargs:ada`. I've tried your scenario (on Linux :smile:)  and got:

> Executing task: alr exec -- gprbuild -P /tmp/myproject/myproject.gpr src/myproject.adb -cargs:ada -gnatef 

Could you find why in your case `-carg` appears?

PS Passing `-cargs -gnatef` instead of `-cargs:ada -gnatef` won't work for projects with C/C++/non-Ada spurces, because `gcc` won't understand `-gnatef`.

**Comment by reznikmm** [comment] 2024-12-18 12:37
I was able to reproduce on Windows! Thank you for the report! As a workaround you can create a `.cmd` file and use it in the custom build task.

**Comment by csaltos** [comment] 2024-12-18 16:35
Thank you @reznikmm for your reply.

My bad, the option is `cargs` not `carg`, I will update the but report.

Yes, the error may be fixed with a custom `.cmd` file or even with a custom `task.json` configuration but the idea is that the extension just works on Windows also, not only Linux.

I propose a possible PR to solve it at https://github.com/AdaCore/ada_language_server/pull/1228

**Comment by eliericha** [comment] 2024-12-19 15:38
Hello @csaltos ,

Thank you for reporting this and proposing a solution. However we think that the solution you propose is perhaps not the best.

In our experiments we're finding that the origin of the issue is that your shell (likely PowerShell) is splitting the `-cargs:ada` argument into `-cargs:` and `ada`. We are going for a simpler fix where we quote `'-cargs:ada'` so that the shell no longer splits it.

Note that the `-cargs:ada` switch has always been supported in all gprbuild versions. It's more accurate to use `-cargs:ada` than `-cargs`.

**Comment by csaltos** [comment] 2024-12-19 16:40
WOW !! ... How you find out that? ... Thank you very much Elie !!

**Comment by eliericha** [comment] 2024-12-19 16:52
You're welcome :) It was @reznikmm who figured it out. The fix will be included in the next release which I will try to publish tomorrow.

Note that it will be a _pre-release_ on the VS Code marketplace which means that by default you won't get it by auto-update. You will have to manually activate the _pre-release_ option on the page of the extension.

**Closed** 2024-12-19 16:53 UTC
Labels: bug
