### ISSUE TITLE
ISO 8859-1 encoded GPR file not recognized

### ISSUE THREAD

**Issue by brownts** [AdaCore/ada_language_server#1130] opened 2023-02-27 18:48 UTC
Starting with v23.0.14, we've noticed some of our GPR files can no longer be handled by the VSCode/ALS extension.  It appears to be related to Latin-1 characters in the GPR file.  Reverting back to v23.0.12 of the extension does not have this problem, so is our current workaround.

This is problematic though as navigation and other functionality is no longer available as a result of this issue.  I assume this is due to the recent switch to using libgpr2 for handling of GPR files as indicated in the release notes.

Attached is a screenshot and reproducer for this issue with a simple project and a Latin-1 character encoding for the gpr file.

[gpr_hello_world_project.zip](https://github.com/AdaCore/ada_language_server/files/10842944/gpr_hello_world_project.zip)

![iso_8859-1_gpr](https://user-images.githubusercontent.com/17529295/221653687-53b7718c-2952-4ff3-a2da-430c4f0ab523.png)

**Comment by JHag6694** [comment] 2023-02-27 20:24
Same problem for me. 

In my case, there was only 1 character in 1 comment of 1 .gpr file. 
So, I have changed the comment to avoid the problem with 23.0.14.

**Comment by reznikmm** [comment] 2023-02-28 10:08
I'm able to reproduce this. I didn't find in the [documentation](https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/gnat_project_manager.html) any mention what encoding the `.gpr` files should be. But since migration to `libgpr2`  `.gpr` are supposed to be UTF-8.

**Comment by brownts** [comment] 2023-02-28 13:25
It would seem reasonable to assume that all gpr-based tools handle gpr files in a consistent manner.  Both gprbuild and gprclean (see VA25-035) handle Latin-1 encoded files, so it would seem logical that ALS would be able to handle those same files too.

**Comment by reznikmm** [comment] 2023-03-22 17:14
Should be fixed in 23.0.15

**Closed by reznikmm** 2023-03-22 17:14 UTC
Labels: help wanted
