### ISSUE TITLE
Toggle comment line not working

### ISSUE THREAD

**Issue by wbullaughey** [AdaCore/ada_language_server#1147] opened 2023-05-27 12:09 UTC
Type: <b>Bug</b>

Ada extension installed
Select Ada source file
Select uncommented line
Do keyboard shortcut (Cmd /)
Line does not get commented

Extension version: 23.0.17
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|64.00GB (14.01GB free)|
|Process Argv|--crash-reporter-id 99f98ccf-de35-4db5-893f-bffa4fe7c188|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AnthonyLeonardoGracio** [comment] 2023-06-05 11:25
Hello @wbullaughey,

We can't reproduce with the latest version of the extension, could you attach a reproducer (i.e: a file with a SLOC)?

Regards,

**Comment by AnthonyLeonardoGracio** [comment] 2024-04-11 16:15
Hello,

We are closing this issue since it can't be reproduced with the latest version on the sources we have tried. Don't hesitate to re-open if with a proper reproducer if you still face the same problem.

Regards,

**Closed by AnthonyLeonardoGracio** 2024-04-11 16:15 UTC
Labels: bug
