### ISSUE TITLE
Formatting a file that fails to compile quite often causes the server to cancel all future requests.

### ISSUE THREAD

**Issue by kevlar700** [AdaCore/ada_language_server#934] opened 2022-04-08 15:22 UTC
Sometimes when formatting a file that cannot build, vscode shows the progress animation for around 30 seconds.

Even after the build is fixed. The Ada language server no longer formats files or responds to hover requests etc. and instead responds with '$/cancelRequest' until a window reload or vscode restart is performed.

**Comment by Joebeazelman** [comment] 2022-06-18 20:10
This is happening me as well. It started happening when I tried to format a file with syntax errors.

**Comment by rami3l** [comment] 2022-07-11 08:06
Probably related: https://github.com/AdaCore/ada_language_server/issues/571

**Comment by nobody-famous** [comment] 2022-08-26 19:24
This makes the extension unusable. Having to constantly reload the window because you hit format out of habit is a non-starter. It's an editor extension. Code being in an invalid state is expected.

**Comment by AnthonyLeonardoGracio** [comment] 2022-09-15 12:29
Hello,

Normally this issue has been fixed: we now reste the formatter's state so that it does not block the Ada Language Server after failing. Have you tried with the latest version of the extension @nobody-famous?

If you can still reproduce, would you be able to give us the gnatpp options you have enabled?

Regards,

**Comment by kevlar700** [comment] 2022-09-15 12:49
I rarely need to restart the language server these days. Though I am now using GNAT Studio CR releases and not vscode.

**Comment by Joebeazelman** [comment] 2022-09-15 14:31
> If you can still reproduce, would you be able to give us the gnatpp options you have enabled?
> 
> 
Is there a new release with the fix, or do I have to build it myself from a commit?  Thanks.

**Comment by nobody-famous** [comment] 2022-09-16 18:15
I do

- alr init --bin hello
- cd hello
- alr build
- code .

After enabling the Ada extension, I open src/hello.adb and start to create a function using the snippet,

`
procedure Hello is
function Name () return Return_Type is
    
begin
    
end Name;
begin
   null;
end Hello;
`

At this point, completions are broken and hitting format causes a pop-up that says a message failed. I then add an argument to the function,

`
procedure Hello is
function Name (X:Integer) return Return_Type is
    
begin
    
end Name;
begin
   null;
end Hello;
`

Hit format and it's dead in the water. Needs a window reload.

**Comment by AnthonyLeonardoGracio** [comment] 2023-05-16 13:09
Hello @nobody-famous,

Your issue is now fixed in the latest version  of the extension. The server won't crash anymore when the formatting fails, and your particular example can now be properly formatted.

Regards,

**Closed by AnthonyLeonardoGracio** 2023-05-16 13:09 UTC
