### ISSUE TITLE
Incorrect coloring of variable names containing numbers

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#697] opened 2021-05-12 02:16 UTC
Sometimes in variable names that contain numbers the number part of the name is colored like a number instead of like a variable name. Visual Studio Code 1.56.0.
[Incorrect coloring of variable names with numbers.pdf](https://github.com/AdaCore/ada_language_server/files/6462984/Incorrect.coloring.of.variable.names.with.numbers.pdf)

**Comment by reznikmm** [comment] 2021-05-12 08:52
Indeed. I'm able to reproduce it.
The syntax highlighting was developed by the community. Feel free to send a pull request if you know how to fix this issue.
On my site I'm going to implement a LSP request for the highlighting when time permits.

**Comment by oscarrutt** [comment] 2021-05-14 09:08
I don't know how to fix it.

**Comment by reznikmm** [comment] 2022-08-17 12:22
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.

**Closed by reznikmm** 2022-08-17 12:22 UTC
