### ISSUE TITLE
Project file loaded too late

### ISSUE THREAD

**Issue by PaulCayard** [AdaCore/ada_language_server#1189] opened 2024-03-22 09:31 UTC
Hi,
when I launch vscode (or I launch command "Developer: Reload Window"):
- if a source file is open in the editor, the following problem is displayed: "No project found in root directory. Please create a project file and add it to the configuration.". (FAIL)
- if editor is empty or a non-ada file (for example "settings.json") is open in the editor, problem is not arisen. (CORRECT)

Anyway, when the problem occurs, project file is correctly loaded and all works fine, except for the error displayed. It seems that vscode try to parse the first source file (that is displayed in the editor window) BEFORE the loading of the project file.

**Comment by AnthonyLeonardoGracio** [comment] 2024-03-22 11:00
Hello @PaulCayard,

I can't reproduce with the latest version (20.0.4) on a simple project. Would you be able to fill a reproducer? That would help us.

Regards,

**Comment by PaulCayard** [comment] 2024-03-22 13:21
Hi, I wasn't able to reproduce it on open source projects.
I can't share the project where problem occurs... How can I help you?

**Comment by AnthonyLeonardoGracio** [comment] 2024-03-22 13:36
I can reproduce on one project, even without having an opened file. it's really weird, not sure what's happening since everything works fine right after... We'll investigate.

**Comment by PaulCayard** [comment] 2024-04-17 06:33
I've just installed v24.0.5 and problem seems fixed. Is it a coincidence or did you work on it?
Thanks anyway!

**Comment by AnthonyLeonardoGracio** [comment] 2024-04-17 08:51
Hello, 

We have changed the way we display messages related to project-loading: we now emit proper LSP diagnostics. I think the fix comes from that work.

Closing the issue them. Thanks for letting us know!

**Closed by AnthonyLeonardoGracio** 2024-04-17 08:51 UTC
Labels: bug
